### ISSUE TITLE
Feature request: escape to Racket code within pages, not templates

### ISSUE THREAD

**Issue by quantum1423** [greghendershott/frog#147]
It would be nice if we could escape to Racket code (like with @) in a Scribble or Markdown page, in the same way we do in templates. That is, I know Scribble allows me to run Racket code, but I want to be able to run a piece of Racket code that generates a (list of) HTML just like in `web-server/templates`.

Would this be possible? It would make certain things a lot nicer: sometimes you want to repeat/parametrize a piece of HTML on multiple pages but not on *all* pages, so it should probably be a Racket function, but really doesn't belong on a template.

**Comment by greghendershott** [comment]
If you mean HTML that would need to go in the `<head>` element, I think the short answer is no.

If you mean HTML that goes in the `<body>` element, I think this would be possible. A slightly different story for the two formats:

- Scribble.
  - Of course you can already use at-expressions. :)
  - Frog simply uses the Scribble-generated HTML as-is (well, extracts the main element with your content from the Scribble page, and inserts it into a Frog page).
  - Therefore, if there is a Scribble function to pass through raw HTML as-is, you can already do this. AFAIK there isn't, now. Possibly because Scribble is supposed to render to various formats besides HTML. Anyway, this would really be a FR for [racket/scribble](https://github.com/racket/scribble).

- Markdown.
  - HTML `<body>` elements are generally acceptable in markdown.
  - A FR for Frog: Run `.md` files through a template pass, just like the `xxx-template.html` files are. (As with those templates, your outer at-expressions responsible for evaluating to a string that gets inserted. You mentioned "a (list of) HTML".  Although you can have Racket code that returns lists of HTML text, you'd need to nest that in say `string-append`.)
  - If that's something you'd definitely use in markdown sources, I could look at adding this.

**Comment by quantum1423** [comment]
It would really be nice if Markdown could be run through template too. It would then be trivial to add support for tables, etc by simply defining a piece of Racket code and then requiring it in the Markdown source.

**Comment by greghendershott** [comment]
OK I can look at that.

BTW I think it would need to be opt-in, per-post.

Using the moral equivalent of a `#lang` line at the top, or, some new item in the meta-data section.

Because this would be bad if run on existing markdown files containing `@`.

**Comment by tger** [comment]
I have been looking for something like this as well. Putting your Racket code in a template and testing for the page url is not so nice and not very modular.

**Comment by greghendershott** [comment]
@tger Just so you know, the proposed feature would only let you vary what goes in the "body" of a page. The `page-template.html` would still control what's around it. Would that still be useful for you?

**Comment by tger** [comment]
Yes. Since currently page-template.html can not put stuff in the body I think the they would complement each other very well.

**Comment by quantum1423** [comment]
I just want to write "macros" (Racket functions) for things like "a picture with a caption", "interlinear gloss", "youtube embed", and things like that. The hack I'm currently working with is to use HTML and an empty div tag with a certain class, which JavaScript then finds and replaces it at "runtime", but it would be *much* better if this sort of task could be done at render-time.

**Comment by greghendershott** [comment]
I'd written:

> BTW I think it would need to be opt-in, per-post.
>
> Using the moral equivalent of a `#lang at-exp` line at the top, or, some new item in the meta-data section.
>
> Because this would be bad if run on existing markdown files containing `@`.

Thinking about this more: It definitely needs to be "opt-in". But instead of this being done via meta-data or the moral equivalent of a `#lang` line -- I think it should use a unique file extension: say `.mdt` instead of `.md`.

Why:

1. This is better than something in the meta-data section, because I could make it work for non-post markdown sources, too. (Those lack any meta-data section.)

2. This is better than the moral equivalent of a `#lang` line, because it preserves a fast path for normal `.md` markdown files where the markdown parser reads directly from the file `input-port`. (Whereas `.mdt` files will first be evaluated as a template to produce a `string`, and the markdown parser reads from that.)

The only drawback I see is that an editor like Emacs won't see `.mdt` as a markdown file. However you could add that suffix. And anyway, things like templates are by definition "multi-mode" sorts of files. Much like HTML files. You might toggle the mode from markdown to Racket to HTML to JavaScript, as needed, because the file contains a mix of these. So, I don't think this is _too_ big a drawback.

@quantum1423 and @tger if you have any feelings please let me know? Meanwhile I'll work ahead for now with the extension approach.

**Comment by greghendershott** [comment]
I pushed a commit only on a new `markdown-template` branch, for now. Mainly I wanted to give you a chance to see the code, and give Travis CI a crack at it. (Although I don't necessarily expect you to futz with using that branch from source, you're welcome to do that, too.)

**Comment by greghendershott** [comment]
Actually I may defer this. There are still corner cases I don't like.

I checked out [the relevant section of the CommonMark spec](http://spec.commonmark.org/0.22/#emphasis-and-strong-emphasis), which goes into rather mind-numbing (but valid) detail. The 12 rules -- and 5 more rules to handle when the first 12 are ambiguous -- are probably the right thing to do, I just don't have time right now to tackle that.

**Comment by greghendershott** [comment]
I posted a comment to the wrong repo/issue. If you got email notified before I deleted it, sorry for the confusion.

**Comment by greghendershott** [comment]
@quantum1423 @tger Although there's no rush (for me), I won't merge to master until/unless I hear back from you.

[Why: 1. Prefer to add only features someone will actually need/use. 2. The doc should be improved; happy to do so, but only if/as needed.]

**Comment by tger** [comment]
No rush for me either but ready when you are.

**Comment by greghendershott** [comment]
As long as I had "the hood open", I took some time to reorganize and improve the documentation generally. Merged.

**Comment by greghendershott** [comment]
p.s. Typically it may take an hour for the Racket package server to notice the change and refresh, so that `raco pkg update frog` will have this for you.

**Comment by greghendershott** [comment]
p.p.s. Thank you for the feature idea @quantum1423 and for your input @tger.

**Comment by greghendershott** [comment]
@quantum1423 wrote:

> I just want to write "macros" (Racket functions) for things like "a picture with a caption", "interlinear gloss", "youtube embed", and things like that. 

Those sound really useful! I'd be very happy to take pull request(s) if you had the time and inclination to add any of these to [`widgets.rkt`](https://github.com/greghendershott/frog/blob/markdown-template/frog/widgets.rkt).
