### ISSUE TITLE
what part(s) of Frog would I need to patch to change certain page-generation logic

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/frog#159]
Specifically, I would like to:
1. Make an `index.html` that is simply a `post-template.html` populated with the most recent posting.
2. Rename what is currently `index*.html` to `archive.html`.

**Comment by greghendershott** [comment]
In terms of existing options (not needing to patch code), I think the
closest would be index-full? = true and posts-per-page = 1.

But that's only close. Ish. Not exactly 1. And it would affect all index
pages (including those for tags). And it doesn't even address 2.

​Frog is definitely calibrated more toward just-works than
ultimately-configurable. That met my needs when I started it. A more
Rackety approach would be a `#lang blog`. Or at least a library of pieces
you could stitch together as needed. I might split go even further; e.g.
instead of a slow buggy implementation of half of `make`, actually use
`make`. Maybe on top of all that redesign it would be possible to preserve
a just-works default configuration.

**Comment by mbutterick** [comment]
FWIW this is for the new `blog.racket-lang.org`. I can see how to do it in Pollen, sure. But I'm pretty close with Frog:

[Post page](http://mbutterick.github.io/racket-lang-org/blog-host/2016/02/racket-v64.html)
[Archive page](http://mbutterick.github.io/racket-lang-org/blog-host/)

Though if you're actively dissuading me from this kind of knob-twisting, I will take the hint ;)

> In terms of existing options (not needing to patch code), I think the
closest would be index-full? = true and posts-per-page = 1.

Though this would supersede the permalink scheme (which I need to preserve for backward compatibility with the old Blogger.com URLs)

**Comment by mbutterick** [comment]
But, let me look at it a little further. It may be that I can either fully Frogify it or patch it outside of Frog.

**Comment by greghendershott** [comment]
Definitely not trying to dissuade you. Just really short on time, at the moment.

The new blog design is beautiful!
