### ISSUE TITLE
No syntax highlighting for scribble posts.

### ISSUE THREAD

**Issue by LeifAndersen** [greghendershott/frog#165]
There is no syntax highlighting for posts written in scribble.

In this case we don't even really need pygments to do the highlighting, as scribble's rendering engine can already do syntax highlighting. (Although I don't know how much of that you use and how much of it you re-built.)

But it would be nice to have syntax highlighting in my code when written in scribble.

**Comment by greghendershott** [comment]
I'm not sure I understand. Frog renders Scribble post `.scrbl` files to HTML as usual, then Frog extracts the "body" to use. You get whatever syntax highlighting normally occurs for forms like `racketblock` and `interaction`.

As one really nice example by @soegaard [this source](https://github.com/soegaard/soegaard.github.io/blob/master/_src/posts/2013-06-21-running-man.scrbl) produces [this result](http://soegaard.github.io/blog/2013/06/21/running-man/).

**Comment by greghendershott** [comment]
p.s. Make sure you have [a `scribble.css` file](https://github.com/greghendershott/frog/blob/master/example/css/scribble.css).

**Comment by sorawee** [comment]
@LeifAndersen I made a patch that might fix this issue. Can you try and see if it fixes the bug you experienced?

**Comment by greghendershott** [comment]
Preface: It's been a couple years since I've worked actively on Frog, so, I'm going to be making mistakes these days.

Case in point: My Sep 12 comment to @LeifAndersen above wasn't helpful. I had actually forgotten about [this way to pygmentize non-Racket code in Scribble docs](https://github.com/greghendershott/frog/issues/91#issuecomment-48512361). @LeifAndersen are you aware of this? Is this what you had tried to do?

@sorawee How I remembered this was checking the file history for `enhance-body.rkt` as part of reviewing your PR #176  (thank you for that!). I'll discuss that there.
