### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by cwebber** [greghendershott/frog#205]
I don't see a COPYING file or etc in this repository.  Could you add one?  What's the license?

**Comment by cwebber** [comment]
I see you have a "license: MIT" button on the README / homepage which is great... but a COPYING file will make it legal.  (And better yet, add copyright headers to files too... but COPYING is most important.)

There are multiple MIT licenses, but I assume you probably mean Expat rather than X11!

**Comment by greghendershott** [comment]
1. The [`LICENSE` file is down in the `frog` collection directory](https://github.com/greghendershott/frog/blob/master/frog/LICENSE). Why down there? So it's included in what's installed on each machine by `raco pkg frog`.

2. I thought I'd linked to that file from the "license: MIT" "badge" in the README -- so that you'd go to it if you click the badge -- but apparently I overlooked it.  I think that's the actionable bug to fix here.

**Comment by cwebber** [comment]
@greghendershott aha great! Maybe also symlink the LICENSE file to the toplevel of the repo?

**Comment by LeifAndersen** [comment]
I agree with this. As is, the LICENSE seems to imply that it only applies to the frog subdirectory, which I doubt is your intent. Even just adding a note in the top level directory would probably help. :)

**Comment by greghendershott** [comment]
I'm catching up on open issues and about to merge commit 6b0d4dd for this.

The commit adds a link from the MIT License "badge" in `README.md` to the `frog/LICENSE` file.

---

I'm _not_ going to do anything with a symlink because I'm nervous that:

- Symlinks won't work right for Windows users.
- It seems it ought to be a relative symlink -- but a quick search suggests GitHub doesn't like those? I don't know, but I don't want to burn cycles researching and experimenting.
