### ISSUE TITLE
Re-generating index.html

### ISSUE THREAD

**Issue by sswatson** [greghendershott/frog#220]
I'm using Frog for a website with no blog posts, and it seems to take some fiddling to get Frog to re-generate index.html from index-template.html in that case. It doesn't even seem to recompile when index-template.html has been changed, which seems like it would be an easy fix.

**Comment by greghendershott** [comment]
Does using `--clean` help -- e.g. `raco frog -cb`?

Not only does this delete generated output files like `index.html`, it clears a build cache.

**Comment by sswatson** [comment]
`raco frog -c` does delete the index.html file, but building afterwards doesn't re-generate it. At least, not for me when I tested it just now. It does re-generate from the Markdown files, though.

**Comment by greghendershott** [comment]
> I'm using Frog for a website with no blog posts

Well I get an F for reading comprehension because I scanned right past that -- sorry!

I honestly don't know how well Frog will support that, status quo. It's a **fr**ozen bl**og** generator and that assumption is baked into the design in various ways. Apparently this is one.

I'm not opposed to generalizing it. In fact, having at least one person using it that way for real -- like you -- would make that a realistic undertaking. But at least in the very near future I won't have time to work on that.

The next few days I don't even have a lot of time to research work-arounds. The only thing that occurs to me quickly is the obvious -- have at least one blog post, even a silly "hey we made a web site" post. I know. Meh.

**Comment by sswatson** [comment]
Ah, so I can just _have_ an empty blog post and get the appropriate behavior. For some reason I had the impression that I needed to add a new blog post to trigger an index.html re-generate, and that felt a bit tedious/hackish. I'm fine with this solution, and I was able to confirm just now that it works. 

I haven't had much trouble using Frog for non-blog purposes. This has been the only real issue. And I'm hardly the most important non-blog Frog user; no less than [pyret.org](http://www.pyret.org) is Frog-based! Actually, that website was my inspiration to start using Frog.
