### ISSUE TITLE
Document uri-prefix

### ISSUE THREAD

**Issue by pmatos** [greghendershott/frog#249]
Variable `uri-prefix` is not documented. I checked, however that's valid and used in the example blog.

**Comment by greghendershott** [comment]
Oh. Yes. I don't remember the history off the top of my head. From a quick glance at the code:

The `uri-prefix` template variable ~= the [`current-uri-prefix` parameter](https://docs.racket-lang.org/frog/parameters.html#%28def._%28%28lib._frog%2Fparams..rkt%29._current-uri-prefix%29%29). It's just "stringified" so that if the parameter value is `#f`, the template variable value is `""`, which is what you'd want using it in a texty template.

That should be added to https://github.com/greghendershott/frog/blob/master/frog/frog.scrbl#L503 so it appears in https://docs.racket-lang.org/frog/templates.html#(part._page-template).

**Comment by greghendershott** [comment]
Looking more carefully: The `uri-prefix` template variable is supplied to all three templates, `{page post index}-template.html`, so all three spots in the doc should be updated.

**Comment by greghendershott** [comment]
As with any doc change, this won't be reflected at https://docs.racket-lang.org/frog/templates.html until the next build server run (normally within 24 hours). However if you `raco update frog` it will should your local docs with the change.
