### ISSUE TITLE
PDF documentation build fails

### ISSUE THREAD

**Issue by rfindler** [greghendershott/frog#258]
Running `raco setup --doc-pdf x frog` generates pdf documentation in the `x` directory, except that the latex code fails. I think this is the relevant output that shows the error:

```
LaTeX Warning: Hyper reference `t:x28def_x28x28lib_x22frogx2fparamsx2erktx22x29
_currentx2dpermalinkx29x29' on page 25 undefined on input line 2070.


! LaTeX Error: Undefined color `grey'.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.2084 ... shell for literal \Scribtexttt{$\sim$}}
                                                  \end{SingleColumn}\end{SVe...

You're in trouble here.  Try typing  <return>  to proceed.
If that doesn't work, type  X <return>  to quit.

```

**Comment by greghendershott** [comment]
Thanks for reporting this.

My initial reaction is that I'm unlikely to fix this because:

- I've never made any effort to test for PDF doc output. (AFAIK the Racket package build server doesn't build/test this, either? So I'm not even sure what the expectation is for packages? I thought this was more at the discretion of the package author?)

- I know nothing about LaTeX except that it has a funny capitalization and pronunciation.

Seriously I think it's good to know this, and I genuinely appreciate having the issue logged, but it seems unlikely I'll look into it (especially as [this project is in low-maintenance mode](https://github.com/greghendershott/frog#what-to-expect-in-the-future)).

**Comment by rfindler** [comment]
I agree it isn't a big deal. I'll make a pull request; feel free to ignore or merge as you wish.

For future reference, grey (and gray, sadly) [aren't in the minimal set of colors available via `color-property`](https://docs.racket-lang.org/scribble/core.html?q=color-property#%28def._%28%28lib._scribble%2Fcore..rkt%29._color-property%29%29) but since rgb values are, it looks like an easy fix.

**Comment by greghendershott** [comment]
Oh! I didn't understand it's just tweaking a color. Thanks for the PR!
